{{ service }}:
    priority: 5 # Lower value means lower priority (Default: 0)
    search:   # Search parameters configuration
    download:
        extract:
        outputs_prefix: /data/
    auth:
        credentials:
            username: '{{ creodias_username }}'
            password: '{{ creodias_password }}'
    # CREODIAS provides and S3 compatible object store service.
    # The S3 storage credentials (aws_access_key_id and aws_secret_access_key)
    # are obtained from the CREODIAS web interface.
    storage:
        region_name: null
        endpoint_url_local: '{{ s3_endpoint_url_local }}'
        endpoint_url_ext: '{{ s3_endpoint_url_ext }}'
        aws_access_key_id: '{{ s3_aws_access_key_id }}'
        aws_secret_access_key: '{{ s3_aws_secret_access_key }}'
        config: {{ config }}
        output_directory: /data/ # TODO: check that this is necessary
        bucket: '{{ bucket }}'
sentinel-hub:
    instance_id: {{ sh_instance_id }}
    sh_client_id: {{ sh_client_id }}
    sh_client_secret: {{ sh_client_secret }}
