# servers_cloud group assumes that an S3 object store is available in the VM

- name: Copy config over
  ansible.builtin.template:
    src: config_eo_service.yml
    dest: '{{ ansible_env.HOME }}/config_eo_service.yml'
    remote_src: no
